workflows:
  default-workflow:
    name: Build Flutter APK
    scripts:
      - name: Unzip project
        script: |
          unzip study_tracker.zip -d ./unzipped
          mv ./unzipped/* ./
          rm -rf ./unzipped
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
